### PR TITLE
Added some AI!

### PR DESCRIPTION
**Pull request by bobomb**
Hey man, I loved your tie so much I made my own, maybe you'll find it interesting! I'm running off a Teensy 2.0 so I've got more flash(32kb) and ram(2.5k), and I've kind of hacked in a super basic AI into this. Perhaps you don't want to pull any of the changes, but I thought you might find it cool anyway. Sadly, it's not super efficient. Using the fastspi2 library it clocks in at 17kb for me, but using the ws2811 library you had comes in at under 8KB, which probably won't fit on your digispark.

Anyway man, thanks for the inspiration and the sheer fun I've had over the past two days playing with this!

### CODE REVIEW

**Comment by madsci1016** [comment]
I've just built Tie.2 with a full Mega328, that should give the needed RAM and flash space. I'll try your code on it an post a video. Did you test it on a hardware setup at all?

Also, I love you commit messages, You and I are very alike.

**Comment by madsci1016** [comment]
BTW, FastSPI is a memory hog because it compiles all supported chip types into the code and that space is wasted. The library I used has a restrictive license, so I'm going to try Adafruit's neopixel library instead.

**Comment by madsci1016** [comment]
Weird, I guess this auto-closed. Anyway, your AI has been merged into my master, Thanks! Compiles to 6.4k, so it would have fit into the Digispark flash. RAM is another story though

**Comment by bobomb** [comment]
I was planning to upgrade to the fastspi2 release candidate which has been super optimized to not compile all chip tipes and compiles much smaller than fastspi I was using, but neopixel works too. I'm glad to be of some help!

**Pull request closed without merging**
